---
title: "FinalAnalysis"
author: "Dohwan"
date: '2021 5 11 '
output: html_document
---

# 1. 데이터 준비
  + https://www.koweps.re.kr:442
  
### 1-1. 패키지 준비
```{r}
library(foreign)
library(dplyr)
library(ggplot2)
library(readxl)
```

### 1-2. 데이터 불러오기
```{r}
raw_welfare <- read.spss("../data/Koweps_hpc10_2015_beta1.sav",to.data.frame = T,fileEncodin="CP949",encoding="UTF-8")
welfare <- raw_welfare
```

### 1-3. 데이터 검토
```{r}
dim(welfare)
#str(welfare)
#View(welfare)
```

#### 1.4. 특성 선택
```{r}
welfare <- rename(welfare, sex=h10_g3, birth=h10_g4, marriage=h10_g10,
                  religion=h10_g11, income=p1002_8aq1, code_job=h10_eco9,
                  code_region=h10_reg7)

welfare <- welfare[, c("sex", "birth", "marriage", "religion", "income",
                       "code_job", "code_region")]
str(welfare)
```

# 2. 탐색적 데이터 분석

### 2-1. 성별에 따른 월급의 차이?
```{r}
# 성별 변수 검토
class(welfare$sex)
table(welfare$sex)
```

```{r}
# 월급 변수 검토
summary(welfare$income)
```

```{r}
qplot(welfare$income)
qplot(welfare$income) + xlim(0,1000)
```


#### 2-1-1. 변수 전처리
```{r}
# 성별 항목에 대한 이름 변경
welfare$sex <- ifelse(welfare$sex==1, "male","female")
table(welfare$sex)
qplot(welfare$sex)
```

```{r}
# 성별 변수에 대한 전처리 : 이상치, 결측치 
table(welfare$sex)

# 만약 성별에 이상치가 같다면
welfare$sex <- ifelse(welfare$sex == 9, NA, welfare$sex)
table(is.na(welfare$sex))
```

```{r}
# 월급변수에 대한 전처리 : 이상치, 결측치
welfare$income <- ifelse(welfare$income %in% c(0,9999), NA, welfare$income)
table(is.na(welfare$income))
```


#### 2-1-2. 결론

```{r}
sex_income <- welfare %>% filter(!is.na(income)) %>% group_by(sex) %>% summarise(mean_income = mean(income))
sex_income
```

```{r}
ggplot(sex_income, aes(sex,mean_income)) + geom_col()
```


### 2-2 나이와 월급의 관계 : 몇살에 월급을 가장 많이 받을까?

```{r}
summary(welfare$birth)
```


```{r}
qplot(welfare$birth)
```

#### 2-2-1. 변수 전처리
```{r}
### 나이 변수에 대한 전처리 : 이상치, 결측치, 파생변수

# 이상치 확인
summary(welfare$birth)

# 결측치 확인
table(is.na(welfare$birth))

# 파생 변수 생성 : age
welfare$age <- 2015 - welfare$birth + 1
summary(welfare$age)
```

```{r}
qplot(welfare$age)
```

#### 2-2-2. 결과
```{r}
age_income <- welfare %>% filter(!is.na(income)) %>% group_by(age) %>% summarise(mean_income=mean(income))
head(age_income)
```

```{r}
ggplot(age_income, aes(age,mean_income)) + geom_line()

```

### 2-3. 연령대에 따른 급여의 차이?

#### 2-3-1. 변수 전처리 : 파생변수 생성
  
  + 초년(young) : 30세 미만
  + 중년(middle) : 30 ~ 59세 이상
  + 노년(old) : 60세 이상
  
```{r}
welfare <- welfare %>% mutate(ageg = ifelse(age<30, "young", ifelse(age<=59, "middle","old")))
table(welfare$ageg)
qplot(welfare$ageg)
```

#### 2-3-2. 결과

```{r}
# 연령대별로 평균 급여
ageg_income <- welfare %>% filter(!is.na(income)) %>% group_by(ageg) %>% summarise(mean_income=mean(income))
ageg_income

```


```{r}
ggplot(ageg_income, aes(ageg, mean_income)) + geom_col() + scale_x_discrete(limits=c("young","middle","old"))
```

### 2-4. 연령대 및 성별에 따른 급여 차이

#### 2-4-1. 연령대 및 성별 월급 차이

```{r}
sex_income <- welfare %>% filter(!is.na(income)) %>% group_by(ageg, sex) %>% summarise(mean_income = mean(income))
sex_income
```
```{r}
ggplot(sex_income, aes(x=ageg, y=mean_income, fill=sex)) + geom_col(position="dodge") + scale_x_discrete(limits= c("young","middle","old"))
```

#### 2-4-2. 나이 및 성별 월급 차이
```{r}
age_sex_income <- welfare %>% filter(!is.na(income)) %>% group_by(age, sex) %>% summarise(mean_income = mean(income))
age_sex_income
```
```{r}
ggplot(age_sex_income, aes(x=age, y=mean_income, col=sex)) + geom_line()
```




